config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"

  resources :tweets

  resources :users, only: [:show]

  resources :followers, only: [:create, :destroy]



 #get 'form', to: 'tweets#new' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
  has_many :users



end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :tweets
  has_many :followers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def index

  end

  def create
    ::Followers::Create.new(user_id: params[:user_id] , follower_id: current_user.id).execute
    redirect_to user_path(params[:user_id])
  end

  def destroy
    ::Followers::Destroy.new(user_id: params[:id], follower_id: current_user.id).execute
    redirect_to user_path(params[:id])

  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
   before_action :authenticate_user!, only:[:new,:create,:edit]


 def new
   p '@@@@@@@@@@@@@@@@' #como un echo pero para terminal

   @tweet=Tweet.new  #inicializando

 end

 def create
   p params #para mirar los parametros enviados por el formulario

   @tweet=current_user.tweets.new tweet_params

   @tweet.save

   redirect_to "/tweets"

 end

 def edit
   @tweet=Tweet.find(params[:id])
   

 end
 
 def update
  @tweet=Tweet.find(params[:id])
  @tweet.update(title: params[:tweet][:title],description: params[:tweet][:description] ) #o por funcion update(tweet_params)
  p '@@@@@@@@@@@@@@@@'
  p tweet_params
 end


 def destroy
    @tweet= Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path
 end



 def index
    @tweets =Tweet.all.decorate

    
 end


 def show
   @tweet=Tweet.find(params[:id]).decorate
 end

 def tweet_params
  params.require(:tweet).permit(:title,:description)

 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show 

        @user=User.find(params[:id]).decorate


        #@current_user = User.find(session[:id]).decorate


        #@tweets =Tweet.where(user_id:@user.id)      
        #@tweets =Tweet.where(user:@user)
        @tweets = @user.tweets
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwiterPruebas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
      <!-- 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> 
      !-->
 <div class="container-fluid " style="background-color:#e3f2fd;">
   <div class="container-md d-flex justify-content-between">
     <% if user_signed_in? %>
       <div class="d-flex align-items-center">
         <%=current_user.email%>
       </div>

       <ul class="nav flex-row d-flex align-items-center justify-content-between">
         <li class="nav-item ">


         </li>

         <li class="nav-item nav-link ">
           <%= link_to'log out', destroy_user_session_path ,data: { turbo_method: :delete }%>
         </li>

         <li class="nav-item nav-link ">
           <%= link_to'account settings', edit_user_registration_path%>
         </li>

     <% else %>
       <ul class="nav row justify-content-end">

         <li class="nav-item nav-link col-2">
           <%= link_to'log in', new_user_session_path%>
         </li>

         <li class="nav-item nav-link col-2">
           <%= link_to'sign up', new_user_registration_path%>
         </li>

     <% end %>
     </ul>


   </div>


 </div>

app/views/tweets/_form.html.erb
<%= form_with model:@tweet  do |form| %>
  <%= form.label "What do  u thigs:" %>
  <%= form.text_field :title %>
  <%= form.text_field :description %>
  <%= form.submit  %>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="container-md ">


  <% @tweets.each do |tweet| %>

    <div class="row">

      <div class="col-8">
        <p><%= link_to tweet.user.email, user_path(tweet.user_id) %></p>

        <p><%= tweet.creation_date %></p>
      </div>


      <div class="col-2">
        <% if !current_user.nil? && current_user.id == tweet.user_id %>
          <%= link_to "EDIT TWEET", edit_tweet_path(tweet.id) %>
          </div>

          <div class="col-2">
            <span><%= link_to "Delete Tweet", tweet, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> </span>
        <% end %>
        </div>
        </div>


    <div class="row">

      <div class="col">
        <%= link_to tweet_path(tweet.id) do %>
          <h2><%= tweet.title %> </h2>
        <% end %>
      </div>
    </div>

    <div class="row">

      <div class="col text-left">
        <p><%= tweet.description %></p>
      </div>

    </div>


  <% end %>
</div>

app/views/tweets/edit.html.erb
<%= render 'tweets/form'%>

app/views/tweets/index.html.erb
<div class="container">

    <div class="row">

        <div class="col">
        <h1>Tweets</h1>
        </div>

        <div class="col-2">
        <%= link_to "CREATE TWEET", "/tweets/new" %>
        </div>

    </div>


    <%= render 'tweets/tweet'%> <%#colection y locals, partial no van con @variableinstancia%>

</div>

app/views/tweets/new.html.erb
<%= render 'tweets/form'%>

app/views/tweets/show.html.erb
<h2><%= @tweet.title%></h2>
<h2><%= @tweet.creation_date%></h2>
<p><%= @tweet.description%></p>

app/views/users/show.html.erb
<p> <%= @user.full_name %> </p>
<p> <%= @user.count_followers %> </p>
<p> <%= @user.count_following %> </p>

  <div>
    <% if @user.find_follower %>
      <%= button_to "Unfollow", follower_path(@user.id), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Follow", followers_path(user_id: @user.id), method: :post, class: "btn btn-info" %>
    <%end %>
  </div>


      <div>
        <% @tweets.each do |tweet| %>
          <div>

            <% if current_user.id == tweet.user_id %>
              <%= link_to "EDIT TWEET", edit_tweet_path(tweet.id) %>
            <% end %>

            <% if current_user.id == tweet.user_id %>
              <span><%= link_to "Delete Tweet", tweet, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %> </span>
            <% end %>

            <%= link_to tweet_path(tweet.id) do %>
              <h2><%= tweet.title %> </h2>
            <% end %>

          </div>

          <p><%= link_to tweet.user.email, user_path(tweet.user_id) %></p>


          <p><%= tweet.description %></p>


        <% end %>


      </div>